export const apiHost = process.env.NODE_ENV === "development" ? "http://localhost:8000" : "https://lenstack.vercel.app"

const endPoints = {
  getapireference: `${apiHost}/api/apireference/getallbyproductname`,
  generatePassKeyEndpoint: `${apiHost}/api/user/generatepasskey`,
  verifyPassKeyEndpoint: `${apiHost}/api/user/verifypasskey`,
  userDetailsEndpoint: `${apiHost}/api/user/userdetails`,
  signOutEndpoint: `${apiHost}/api/user/signout`,
  subscribeEndpoint: `${apiHost}/api/subscription/subscribe`,
  activateTrialEndpoint: `${apiHost}/api/subscription/activatetrial`,
  getSubscriptionConfigEndpoint: `${apiHost}/api/subscription/getsubscriptionconfig`,
  getProductConfigEndpoint: `${apiHost}/api/common/getproductconfig`,
  getSecretConfig: `${apiHost}/api/common/getsecretconfig`,
  createWorkspace: `${apiHost}/api/workspace/create`,
  findMyWorkspaces: `${apiHost}/api/workspace/findmyworkspaces`,
  switchWorkspace: `${apiHost}/api/workspace/switch`,
  airlakeFiltersEndpoint: `${apiHost}/api/products/airlake/filters`,
  airlakeFindDatasetsEndpoint: `${apiHost}/api/products/airlake/finddatasets`,
  airlakeViewDatasetsEndpoint: `${apiHost}/api/products/airlake/viewdataset`,
  airlakeFindSimilarDatasetsEndpoint: `${apiHost}/api/products/airlake/findsimilardatasets`,
  airlakeDataApiEndpoint: `${apiHost}/api/products/airlake/dataapi`,
  edgepayCreateTxEndpoint: `${apiHost}/api/products/edgepay/createtx`,
  frostlakeCreateProjectEndpoint: `${apiHost}/api/products/frostlake/createproject`,
  frostlakeGetProjectsEndpoint: `${apiHost}/api/products/frostlake/getprojects`,
  frostlakeViewProjectEndpoint: `${apiHost}/api/products/frostlake/viewproject`,
  frostlakeDeleteProjectEndpoint: `${apiHost}/api/products/frostlake/deleteproject`,
  frostlakeCreateAnalyticsEndpoint: `${apiHost}/api/products/frostlake/createanalytics`,
  hexscanAnalyzerEnpoint: `${apiHost}/api/products/hexscan/analyzer`,
  hyperedgeCreateDbEndpoint: `${apiHost}/api/products/hyperedge/createdb`,
  hyperedgeGetMyDbsEndpoint: `${apiHost}/api/products/hyperedge/getmydbs`,
  hyperedgeViewDbEndpoint: `${apiHost}/api/products/hyperedge/viewdbfromplatform`,
  hyperedgeDeleteDbEndpoint: `${apiHost}/api/products/hyperedge/deletedb`,
  hyperedgeCreateKvEndpoint: `${apiHost}/api/products/hyperedge/createkv`,
  hyperedgeDeleteKvEndpoint: `${apiHost}/api/products/hyperedge/deletekv`,
  snowlakeCreateTxEndpoint: `${apiHost}/api/products/snowlake/createtx`,
  swapstreamCreateTxEndpoint: `${apiHost}/api/products/swapstream/createtx`,
  swapstreamTokenConfigEndpoint: `${apiHost}/api/products/swapstream/getswapstreamtokenconfig`,
}

export default endPoints