enum Constants {
  BrandName = "Lenstack",
  HomeHeader1 = "Build, Ship & Scale",
  HomeHeader2 = "Powered by Blockchain",
  HomeIntro1 = "Start with 30 days free trial, with 10k credits",
  HomeIntro2 = "There’s no upfront commitment",
  HomeIntro3 = "Upgrade on demand, Starting at 1.99 MATIC/month",
  ConnectionErrorMessage = "Connection Error",
  IdentityVerificationMessage = "Verifying Identity",
  ErrorMessage = "404, Lost",
  ToastSuccess = "Done",
  ToastError = "Something went wrong",
  TransactionError = "Transaction Error",
  TransactionSuccess = "Transaction Success",
  TokenPurchaseSuccess = "You have successfully purchased token",
  TokenPurchaseFailure = "Error purchasing token",
  TokenSellSuccess = "You have successfully sold token",
  TokenSellFailure = "Error selling token",
  CopiedToClipBoard = "Copied to Clipboard",
  InvalidPasskey = "Invalid Pass Key",
  IdentityVerificationSuccess = "Identity Verified",
  DefaultNftImage = "https://cdn-icons-png.flaticon.com/512/8133/8133529.png",
  PolygonScanBaseUri = "https://mumbai.polygonscan.com/nft",
  OpenseaBaseUri = "https://testnets.opensea.io/assets/mumbai",
  MumbaiFaucetUri = "https://mumbaifaucet.com",
  LinkedinUri = "https://www.linkedin.com/in/arnhazra",
  LenstackNPAWalletAddress = "0xC9bd090E7478422eA19cAeE5c9843ED4c1284DdF"
}

export default Constants