import { config } from "dotenv"
config({ path: "../../.env" })

export const envConfig = {
  apiPort: process.env.API_PORT,
  brandName: process.env.BRAND_NAME,
  platformDbURI: process.env.PLATFORM_DB_URI,
  analyticsDbURI: process.env.ANALYTICS_DB_URI,
  copilotDbURI: process.env.COPILOT_DB_URI,
  dataexchangeDbURI: process.env.DATAEXCHANGE_DB_URI,
  kvstoreDbURI: process.env.KVSTORE_DB_URI,
  ledgerscanDbURI: process.env.LEDGERSCAN_DB_URI,
  nftstudioDbURI: process.env.NFTSTUDIO_DB_URI,
  swapDbURI: process.env.SWAP_DB_URI,
  walletDbURI: process.env.WALLET_DB_URI,
  redisSocketHost: process.env.REDIS_SOCKET,
  redisPassword: process.env.REDIS_PASSWORD,
  redisPort: process.env.REDIS_PORT,
  geminiAPIKey: process.env.GEMINI_API_KEY,
  alchemyGateway: process.env.ALCHEMY_WEB3_GATEWAY,
  infuraGateway: process.env.INFURA_WEB3_GATEWAY,
  quicknodeGateway: process.env.QUICKNODE_WEB3_GATEWAY,
  polygonscanSecretKey: process.env.POLYGONSCAN_SECRET_KEY,
  passkeyHashingKey: process.env.PASSKEY_HASHING_KEY,
  redirectURI: process.env.GCLOUD_REDIRECT_URI,
  gcloudClientId: process.env.GCLOUD_CLIENT_ID,
  gcloudClientSecret: process.env.GCLOUD_CLIENT_SECRET,
  refreshToken: process.env.GCLOUD_REFRESH_TOKEN,
  mailerEmail: process.env.MAILER_EMAIL,
  nftContractAddress: process.env.NFT_CONTRACT_ADDRESS,
  authPrivateKey: process.env.AUTH_RSA_PRIVATE_KEY,
  authPublicKey: process.env.AUTH_RSA_PUBLIC_KEY,
}