export const uiConstants = {
  brandName: "ArcStack",
  homeHeader: "Build, Ship & Scale with",
  homeIntro: "Start with free AS0 plan, no upfront commitment, Upgrade to AS1 at ₹99/month",
  connectionErrorMessage: "Connection Error",
  authVerificationMessage: "Verifying Auth",
  errorMessage: "404, Lost",
  toastSuccess: "Done",
  toastError: "Something went wrong",
  transactionError: "Transaction Error",
  transactionSuccess: "Transaction Success",
  tokenPurchaseSuccess: "You have successfully purchased token",
  tokenPurchaseFailure: "Error purchasing token",
  tokenSellSuccess: "You have successfully sold token",
  tokenSellFailure: "Error selling token",
  copiedToClipBoard: "Copied to Clipboard",
  invalidPasskey: "Invalid Pass Key",
  authVerificationSuccess: "Auth Verified",
  amoyFaucetUri: "https://faucet.polygon.technology/",
  linkedinUri: "https://www.linkedin.com/in/arnhazra",
  githubRepoUri: "https://github.com/arnhazra/arcstack",
}