export const uiConstants = {
  brandName: "ArcStack",
  homeHeader: "Build, ship & scale Powered by",
  homeIntro: "Start with a hobby plan, for free, no upfront commitment, Upgrade on demand, Starting at ₹99/month",
  connectionErrorMessage: "Connection Error",
  authVerificationMessage: "Verifying Auth",
  errorMessage: "404, Lost",
  toastSuccess: "Done",
  toastError: "Something went wrong",
  transactionError: "Transaction Error",
  transactionSuccess: "Transaction Success",
  tokenPurchaseSuccess: "You have successfully purchased token",
  tokenPurchaseFailure: "Error purchasing token",
  tokenSellSuccess: "You have successfully sold token",
  tokenSellFailure: "Error selling token",
  copiedToClipBoard: "Copied to Clipboard",
  invalidPasskey: "Invalid Pass Key",
  authVerificationSuccess: "Auth Verified",
  defaultNftImage: "https://cdn-icons-png.flaticon.com/512/8133/8133529.png",
  polygonScanBaseUri: "https://mumbai.polygonscan.com/nft",
  openseaBaseUri: "https://testnets.opensea.io/assets/mumbai",
  mumbaiFaucetUri: "https://www.alchemy.com/faucets/polygon-mumbai",
  linkedinUri: "https://www.linkedin.com/in/arnhazra",
  githubRepoUri: "https://github.com/arnhazra/arcstack",
  npaWalletAddress: "0xC9bd090E7478422eA19cAeE5c9843ED4c1284DdF"
}