export const uiConstants = {
  brandName: "ArcStack",
  homeHeader: "Build what’s next",
  homeIntro: "Get tools to take care of the busywork and streamline innovation",
  homeIntro2: "Start with a free tier, Upgrade to higher tier on demand",
  connectionErrorMessage: "Connection Error",
  authVerificationMessage: "Verifying Identity",
  errorMessage: "404, Lost",
  toastSuccess: "Action Success",
  toastError: "Something went wrong",
  transactionError: "Transaction Error",
  transactionSuccess: "Transaction Success",
  notification: "Notification",
  tokenPurchaseSuccess: "You have successfully purchased token",
  tokenPurchaseFailure: "Error purchasing token",
  tokenSellSuccess: "You have successfully sold token",
  tokenSellFailure: "Error selling token",
  copiedToClipBoard: "Copied to Clipboard",
  invalidPasskey: "Invalid Pass Key",
  authVerificationSuccess: "Identity Verified",
  linkedinUri: "https://www.linkedin.com/in/arnhazra",
  githubRepoUri: "https://github.com/arnhazra/arcstack",
}