name: Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the version to match your Next.js app's requirements

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Install project dependencies
        run: npm install

      - name: Build the Next.js app
        working-directory: api
        run: |
          npm install
          CI=false npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope client # Use the --scope flag to specify the client directory
