name: DEV CI-CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
on:
  push:
    branches:
      - develop

jobs:
  DEV-CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Build Server application
        working-directory: apps/server
        run: |
          npm install
          CI=false npm run build

      - name: Build Client application
        working-directory: apps/client
        run: |
          npm install
          CI=false npm run build

      - name: Configure packages
        working-directory: apps/server
        run: |
          npm install --global json
          json -I -f package.json -e "delete this.devDependencies"

      - name: Build Movement
        run: |
          mkdir dist
          cp -r apps/server/package.json dist/package.json
          cp -r apps/server/dist/. dist
          mv apps/client/out dist/client

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
