enum Constants {
  HomeHeader1 = "Build, Ship & Scale",
  HomeHeader2 = "Powered by Blockchain.",
  HomeIntro1 = `Start with 30 days free trial, with 10k credits. There’s no upfront commitment.`,
  HomeIntro2 = `Upgrade on demand, Starting at 1.99 MATIC/month`,
  ConnectionErrorMessage = `Connection Error`,
  IdentityVerificationMessage = `Verifying Identity`,
  ErrorMessage = "404, Lost",
  ToastSuccess = "Done",
  ToastError = "Something went wrong",
  TransactionError = "Transaction Error",
  TransactionSuccess = "Transaction Success",
  TokenPurchaseSuccess = "You have successfully purchased token",
  TokenPurchaseFailure = "Error purchasing token",
  TokenSellSuccess = "You have successfully sold token",
  TokenSellFailure = "Error selling token",
  UnknwonError = "Unknown error",
  CopiedToClipBoard = "Copied to Clipboard",
  InvalidPasskey = "Invalid Pass Key",
  IdentityVerificationSuccess = "Identity Verified",
  DefaultNftImage = "https://cdn-icons-png.flaticon.com/512/8133/8133529.png",
  PolygonScanBaseUri = "https://mumbai.polygonscan.com/nft",
  OpenseaBaseUri = "https://testnets.opensea.io/assets/mumbai",
  AppBaseUri = "https://lenstack.vercel.app",
  MumbaiFaucetUri = "https://mumbaifaucet.com",
  LinkedinUri = "https://www.linkedin.com/in/arnhazra",
}

export default Constants